version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    entrypoint: docker/server/entrypoint.sh
    environment:
      - IN_DOCKER=True
      - DATABASE=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cisco
      - POSTGRES_PASSWORD=cisco
      - POSTGRES_DB=cisco
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    command: yarn start
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - 3000:3000
    stdin_open: true

volumes:
  postgres_data:
